# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XiaoBao' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XiaoBao

# pod 'SDWebImage'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'MJExtension'

pod 'RESideMenu'
# pod 'MMDrawerController'
pod ‘UMengUShare/UI’
pod ‘UMengUShare/Social/Sina'
pod ‘UMengUShare/Social/WeChat'
pod ‘UMengUShare/Social/QQ'
pod ‘UMengUShare/Social/Twitter'
pod ‘UMengUShare/Social/TencentWeibo'
pod ‘UMengUShare/Social/YouDao'
pod ‘UMengUShare/Social/EverNote'
pod ‘UMengUShare/Social/SMS'
pod ‘UITableView+FDTemplateLayoutCell’

pod 'YYWebImage'
pod 'YYCategories'

# pod ‘FMDB’
pod 'Realm'

# pod 'AMScrollingNavbar'
pod 'SDCycleScrollView'
pod ‘GPUImage’
end
