# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XiaoBao' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XiaoBao

# pod 'SDWebImage'
# pod 'RESideMenu'
# pod ‘FMDB’
# pod ‘LTNavigationBar’
# pod 'SDWebImage'
# pod 'AMScrollingNavbar'
# pod 'DZNEmptyDataSet'
# pod 'SDCycleScrollView'
# pod ‘GPUImage’
# pod "MWPhotoBrowser"

pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'MJExtension'
pod 'MMDrawerController'
pod ‘UITableView+FDTemplateLayoutCell’
pod 'FDFullscreenPopGesture'
pod 'YYWebImage'
pod 'YYCategories'
pod 'Realm'
pod ‘DKNightVersion’
pod 'pop'
pod 'IDMPhotoBrowser'
# pod 'MLeaksFinder' 
# pod 'Bugly'
end
